version: "3.9"

services:
  postgres:
    container_name: postgres-14
    image: postgis/postgis:14-3.2-alpine
    shm_size: 2gb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: desafio
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432